### PR TITLE
add octave band options in blender plugin

### LINKED ISSUE #67: add octave and third octave option in blender plugin
the idea is to add two options in the frequnecy dropdown (`frequencyVectorType`) for third-ocatave and ocatve bands. `minFrequency`  and `maxFrequency` defines the limits and `frequencyVectorValue` is not needed in this case.

### PR DESCRIPTION
**Pull request by ahms5**
closes #67
add 2 more options in blender addon for exact and nominal n-th octave bands. For nominal 1 and 3 is supported for exact all kinds.

### CODE REVIEW

**Comment by SDX-LV** [comment]
Question - will this octave step be compatible with SOFA HRIR format? Or will it need a special exception?

**Comment by f-brinkmann** [comment]
It can be written to SOFA Conventions of data type TF, but can not be converted to FIR. But that shouldn't be an issue. If you are interested in results in octave bands you usually do not want IRs as a result

**Comment by ahms5** [comment]
my intention was also to extend this tool and make it more open for other purposes than HRTFs

**Comment by SDX-LV** [comment]
Sounds good, just please make it obvious that if this option is selected the HRIR will not be possible. So that beginners do not get in trouble with this.

**Comment by f-brinkmann** [comment]
We could add a test directly to mesh2input.py. Currently we only do this in compute HRIRs:

```python
if any(np.abs(np.diff(frequencies, 2)) > .1) or frequencies[0] < .1:
        raise ValueError(
            ('The frequency vector must go from f_1 > 0 to'
             'f_2 (half the sampling rate) in equidistant steps.'))
```

The variable name might be different though and it should be a separate pull.

**Comment by f-brinkmann** [comment]
Implemented in https://pypi.org/project/mesh2scattering/

**Pull request closed without merging**
