### PR TITLE
Add numcalcmanager

### PR DESCRIPTION
**Pull request by jeffrey-thomsen**
NumCalcManager.py now accepts key-value command line arguments

### CODE REVIEW

**Comment by SDX-LV** [comment]
Hi, notice that in the end of the script there is the "GNU Lesser General Public License" copied from one of the Mesh2HRTF scripts at the time.

**Comment by f-brinkmann** [comment]
@SDX-LV I did some changes (hopefully improvements). If you want to use this version in your tools, I am happy to do a merge request on sourceforge.

I did flake8 styling and renamed variables to lower case - sorry that is why everything looks as if it has been changed, when really it did not. The substantial changes are:

- I added command line input for all parameters, you can now for example call `python numcalc_manager.py --max_instances 4` without the need to change the content of the file.
- The above means that you can also script `project_path` (previously `start_path`) and there is no need to copy numcalc_manager to the project directory (it can still be done though and the old default still works)
- `python numcalc_manager.py -h` now prints a brief documentation
- I added the parameter `numcalc_path`. This makes copying NumCalc.exe and other files to the source_* folders obsolete (see changed NumCalc calls using `subprocess`). Moreover, this made the parameter `cleanup_after_finish` obsolete.
- I unified the parameters `auto_set_max_instances` and `max_instances`
- I styled the messages and now also write them to a log file.
- I added an option to not wait for user input in case of errors (default maintains your original behaviour)
- I fixed what I think were bugs with a non-initialized variable and an error that does not need to be thrown (commit [952ff39](https://github.com/Any2HRTF/Mesh2HRTF/pull/6/commits/952ff39c15731b727ed637985f0b3ee88e193c67)). I ran into that because I used a test project where instances finish quickly - but I hope this also works for all other projects.

I saw your comment on trying to make the RAM usage even more efficient. Wolfgang had the idea of adding a NumCalc command line parameter to only estimate the required RAM for each frequency. If this works this might be a way to improve the efficiency and make detecting the NumCalc instance that consumes the most RAM obsolete.

**Comment by SDX-LV** [comment]
Hi Fabian, looks like a very nice upgrade with a lot of useful additions - a proper v4.0 :) 
Let's cover some points:

1. The input parameters are great - they extend functionality without breaking the "double-click" operation from a graphical OS.
2. No worries about the "[Mesh2HRTF-Tools](https://sourceforge.net/projects/mesh2hrtf-tools/)" - as soon as NumCalcManager is included in the main repository, I will replace it with a link to the new location and there will be no duplicates.
3. This commit is not harmless: [removed repeated check_project() call](https://github.com/Any2HRTF/Mesh2HRTF/pull/6/commits/403c8cd89153946862e9eff3f816651a0159f353) If this check is not done before the main loop then you do not get information how many unfinished projects are in the queue. I frequently leave finished projects in the same folder, but with this check Manager always knows which project are Unfinished and the rest is confirmed as "already complete". It literally takes a second extra, but gives useful status info.
4. The [unjustified error](https://github.com/Any2HRTF/Mesh2HRTF/pull/6/commits/952ff39c15731b727ed637985f0b3ee88e193c67) may not be necessary after all the new changes, but it was meant to gracefully report that the first NumCalc instance crashed. It happened quite often to me that NumCalc errors-out in the first few seconds, plus it can happen if the NumCalc executable is not working in general.  That check can only cause issues if you run instances that are finished faster than `"--wait_time"`, but in that case also the autodetect of CPU `"--max_instances"` will crash (that crash can be resolved by moving CPU usage check from the start of the 2nd loop to the end of the 1st loop, before the timeout for initialization)
5. Regarding more efficient RAM usage - there is still some room for improvement, but you would need to know in advance how much memory each instance will need and it would require **almost complete re-write** of the the way instances are scheduled and monitored, so I would not do it :) Note that in my experience both CPU load and RAM estimates from Windows may not be 100% reliable, but in practice it worked very well even with occasional "one-too-many" instances launched.
6. I did notice that at very low frequencies instances start to use more RAM than at ~1000Hz - it is a bit counter-intuitive, but again I did not notice performance issues from slight RAM overload.

**Comment by f-brinkmann** [comment]
Hi Sergejs,

thanks for the feedback

3. I agree that its nice to have an overview of what instances will be run and will reintroduce the repeated call to `check_project`
4. I even got the error when setting `--wait_time` to 0. It might be a rare case, but I would prefer if the script works well for all cases. What would you say if call `check_project` again after the main loop to detect missing or crashed instances that way?
5. We would know the estimated RAM usage of each instance ahead in this case. If Wolfgang gets to implement this I would give it a try in a separate pull and we could compare the two versions.
6. That is because NumCalc switches to the Single-Level method for low frequencies. I was wondering how robust numcalc_manager is towards this. It might be problematic to overload the RAM if you compute on a cluster. This would be another advantage of knowing the RAM usage ahead.

I was also thinking about the automatic `--max_instances` estimate. Would it decrease performance, if we used `max_instances = multiprocessing.cpu_count()`. I think the RAM is the more restricting constraint and the OS should schedule processes is we overload the CPU. This might make the code more robust as well.

**Comment by SDX-LV** [comment]
Hi Fabian,

3. ok
4. I think that error message was not so important - if it causes trouble on some platform or special case, just take it away. Regarding re-running `check_project` in the end - it is a great idea in general. Then Manager can give a heads-up in case some instances had problems or not (for some error types).
5. More efficiency is nice, just notice that it will be a big re-write again, comparable to the rewrite to the new project structure. If you and Wolfgang have time for this, then it can only get better. I think you can gain extra 10-20% simulation time reduction (a guess). With current NumCaclManager v3.11 and standard "hrtf_mesh_grading" parameters for head-only I got both ears simulated in 3 hours (up to 5 hours in worst case) on not-the-latest 16-core intel CPU with 64GB RAM.  I am quite happy - day and night difference compared to my early trials without Manager...
6. OK, I saw that it was not perfect, but I actually monitored Windows task manager and did not notice major RAM overloads - it worked out well.  If you must absolutely not exceed max RAM allocation, it is possible to set higher `"--ram_safety_factor"`  to for example 1.3.

With max instance estimate I don't remember exactly why I went with CPU usage approach. I think on my CPU I did not see a clear relationship between typical Numcalc instance CPU % load and number of cores. If you base estimate on logical CPUs, then it may not account for that hyperthreading cores and especially latest Intel big & small cores are not exactly linearly scalable 
(`single_NumCalc_CPU_load * cpu_count() >> 100%`)    Again, there may be improvement potential left there, but I suggest to first experiment some more with existing code and then decide if it needs improvement.

**Comment by f-brinkmann** [comment]
Agreed - implemented changes as suggested.  The final check at the end now raises an error if any unfinished instances were detected. I will try numcalc_manager on our cluster to see if it also works there...

**Comment by SDX-LV** [comment]
Hi Fabian, I would suggest to keep the `numcalc_manager_b.py` as it is - without deeper integration with Python API. 

**Main reason:**
numcalc_manager only needs "psutil" and NumCalc, so it can be quite safely installed into the main Python environment on any computer. While the mesh2hrtf Python API has a lot of big dependencies which are also version sensitive and therefore should be installed into virtual environments which again makes the installation more complex if you need to deploy NumCalc on lots of cluster nodes or simply on many available computers around the campus. 

So if the manager script remains independent from the mesh2hrtf API it will help a lot with quick deployments on machines that are only used to run simulations. Plus less work to refactor code - it already is self-sufficient right now :)

**Comment by f-brinkmann** [comment]
Hi Sergejs,

unfortunately the current version already uses the Mesh2HRTF Python API to read the information from `Memory.txt`. However, since everyone using Mesh2HRTF with Python already knows how to set up the API, I hope that setting it up on multiple machines is not to big of an issue (it could also be scripted to avoid annoying and repetitive work). I'll thus continue with the integration, because it also has the advantage of ``numcalc_manager`` showing up in the online documentation, and hopefully making it easier to recognize.

**Comment by SDX-LV** [comment]
No, there is no reason. I just did not know about that option when I first wrote NumCalcManager.

**Pull request merged**
