### PR TITLE
wait for instances of NumCalc to finish before processing next project

### PR DESCRIPTION
**Pull request by marclava**

### CODE REVIEW

**Comment by marclava** [comment]
My little change worked. My laptop have 32Gb of RAM, and because the last instances of both projects (left and right) required 18G, it was not possible to run more than one NumCalc instance. So for my use case it was good enough, but it would be sub-optimal on a computer with more RAM.

Still, looking at manage_numcalc.py, I'm tempted to refactor it (in a different module named numcalc_manager.py). If you don't mind...

Also, I tried to add multi-processing to NumCalc using OpenMP; unfortunately it was slower... Multi-processing is tricky.

**Comment by f-brinkmann** [comment]
Good to hear. I wait for Sergejs to respond as well. I'd prefer a solution that is robust and fast. But robust and slightly slower would be better than buggy of course. What would you go for in the re-factoring? I'm not sure if it would make sense to have different functions with very similar name and behavior in the package. So I'd rather improve what we have than end up with two versions

**Comment by marclava** [comment]
I agree; the new name would be temporary, in a feature branch, to be renamed to the original name if merged into the develop branch. The behavior would be the same or very similar, with the same API, no changes required to manage_numcalc_script.py. It'd be an exercise (maybe useful), and I would not push the branch until something works well...

**Comment by f-brinkmann** [comment]
Sure that would be fine. We could gather some test cases and see if we can get a speed up to decide if we want to change the current version

**Comment by marclava** [comment]
But still, I believe that my little PR would easily fix an important usability issue (until something better is proposed).

**Comment by f-brinkmann** [comment]
This is what I had in mind: https://github.com/Any2HRTF/Mesh2HRTF/tree/bugfix/manage_numcalc

**Comment by SDX-LV** [comment]
Sorry, I completely missed this conversation previously, and it seems it is now a bit outdated - https://github.com/Any2HRTF/Mesh2HRTF/issues/75

Yes I did add the part to start next project while the instances of the previous one are still running. Without this feature, we are loosing 5 or more minutes of processing time for every switch to a new project in the queue. I don't remember how it was implemented, so of course there may be bugs there to fix.

**Comment by marclava** [comment]
Maybe my new script will help; I wrote it from scratch, trying to integrate most functionalities of the original script; it may not behave the same, but so far it seems to work quite well! Feel free to ask for a PR, I'd be very glad to contribute.

**Pull request closed without merging**
