### PR TITLE
Add checks for isolated and duplicate nodes

### PR DESCRIPTION
**Pull request by f-brinkmann**
Add checks for isolated and duplicate nodes. Cloes #78 and #80 

@Katarina-Poole can you check if this detects the problem you had? You can test by taking the mesh2input.py from this branch, re-import the Mesh2HRTF add-on in Blender, and export your project again.

- [ ] finish tests

### CODE REVIEW

**Comment by Katarina-Poole** [comment]
@f-brinkmann just tried to export in blender with that mesh2input.py after re-importing the addon in blender and now running into this export error in blender:

```


{'FINISHED'}
{'FINISHED'}
{'CANCELLED'}
{'FINISHED'}
Info: No orphaned data-blocks to purge
Info: Saved "3d Model.blend"
Error: Python: Traceback (most recent call last):
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 181, in execute
    return ExportMesh2HRTF.save(self, context, **keywords)
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 404, in save
    filepath1, evaluationGrids, len(obj.data.vertices))
AttributeError: 'Camera' object has no attribute 'vertices'
Location: C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py:113

Traceback (most recent call last):
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 181, in execute
    return ExportMesh2HRTF.save(self, context, **keywords)
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 404, in save
    filepath1, evaluationGrids, len(obj.data.vertices))
AttributeError: 'Camera' object has no attribute 'vertices'
Traceback (most recent call last):
  File "<blender_console>", line 24, in <module>
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 181, in execute
    return ExportMesh2HRTF.save(self, context, **keywords)
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 404, in save
    filepath1, evaluationGrids, len(obj.data.vertices))
AttributeError: 'Camera' object has no attribute 'vertices'
Location: C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py:113
```

**Comment by f-brinkmann** [comment]
for some reaseon your *Reference* object does not seem to selected. Can you try to change `len(obj.data.vertices)` in line 404 with `len(bpy.context.scene.objects["Reference"].data.vertices)`.

**Comment by Katarina-Poole** [comment]
Changed and now its throwing this error (looks like its finding the duplicate nodes?):

```
{'FINISHED'}
{'CANCELLED'}
{'CANCELLED'}
{'FINISHED'}
Info: No orphaned data-blocks to purge
Info: Saved "3d Model.blend"
Error: Python: Traceback (most recent call last):
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 181, in execute
    return ExportMesh2HRTF.save(self, context, **keywords)
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 403, in save
    _check_evaluation_grids(
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 660, in _check_evaluation_grids
    raise ValueError((
ValueError: The nodes in the evaluation grids must have unique IDs (the numbers in the first column of Nodes.txt). But at least one duplicate ID was found.
Location: C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py:113

Traceback (most recent call last):
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 181, in execute
    return ExportMesh2HRTF.save(self, context, **keywords)
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 403, in save
    _check_evaluation_grids(
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 660, in _check_evaluation_grids
    raise ValueError((
ValueError: The nodes in the evaluation grids must have unique IDs (the numbers in the first column of Nodes.txt). But at least one duplicate ID was found.
Traceback (most recent call last):
  File "<blender_console>", line 24, in <module>
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 181, in execute
    return ExportMesh2HRTF.save(self, context, **keywords)
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 403, in save
{'FINISHED'}
{'CANCELLED'}
{'CANCELLED'}
{'FINISHED'}
Info: No orphaned data-blocks to purge
Info: Saved "3d Model.blend"
Error: Python: Traceback (most recent call last):
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 181, in execute
    return ExportMesh2HRTF.save(self, context, **keywords)
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 403, in save
    _check_evaluation_grids(
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 660, in _check_evaluation_grids
    raise ValueError((
ValueError: The nodes in the evaluation grids must have unique IDs (the numbers in the first column of Nodes.txt). But at least one duplicate ID was found.
Location: C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py:113

Traceback (most recent call last):
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 181, in execute
    return ExportMesh2HRTF.save(self, context, **keywords)
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 403, in save
    _check_evaluation_grids(
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 660, in _check_evaluation_grids
    raise ValueError((
ValueError: The nodes in the evaluation grids must have unique IDs (the numbers in the first column of Nodes.txt). But at least one duplicate ID was found.
Traceback (most recent call last):
  File "<blender_console>", line 24, in <module>
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 181, in execute
    return ExportMesh2HRTF.save(self, context, **keywords)
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 403, in save
```

**Comment by Katarina-Poole** [comment]
Changed and now its throwing this error (looks like its finding the duplicate nodes?):

```
{'FINISHED'}
{'CANCELLED'}
{'CANCELLED'}
{'FINISHED'}
Info: No orphaned data-blocks to purge
Info: Saved "3d Model.blend"
Error: Python: Traceback (most recent call last):
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 181, in execute
    return ExportMesh2HRTF.save(self, context, **keywords)
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 403, in save
    _check_evaluation_grids(
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 660, in _check_evaluation_grids
    raise ValueError((
ValueError: The nodes in the evaluation grids must have unique IDs (the numbers in the first column of Nodes.txt). But at least one duplicate ID was found.
Location: C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py:113

Traceback (most recent call last):
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 181, in execute
    return ExportMesh2HRTF.save(self, context, **keywords)
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 403, in save
    _check_evaluation_grids(
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 660, in _check_evaluation_grids
    raise ValueError((
ValueError: The nodes in the evaluation grids must have unique IDs (the numbers in the first column of Nodes.txt). But at least one duplicate ID was found.
Traceback (most recent call last):
  File "<blender_console>", line 24, in <module>
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 181, in execute
    return ExportMesh2HRTF.save(self, context, **keywords)
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 403, in save
    _check_evaluation_grids(
  File "C:\Users\Kat\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\mesh2input.py", line 660, in _check_evaluation_grids
    raise ValueError((
ValueError: The nodes in the evaluation grids must have unique IDs (the numbers in the first column of Nodes.txt). But at least one duplicate ID was found.
Location: C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py:113
```

**Comment by f-brinkmann** [comment]
Yes, great. That means it works. I'll merge as soon as I finished the tests...

**Pull request merged**
