### PR TITLE
Add numcalcmanager fx

### PR DESCRIPTION
**Pull request by SDX-LV**
Some small changes. Including bugfix  `if ram_required * ram_safety_factor <= ram_available:`

### CODE REVIEW

**Comment by f-brinkmann** [comment]
This Pull is on hold during the summer break

**Review by f-brinkmann — CHANGES_REQUESTED** [review]
Thanks for the effort. I'm in favor of 2 of the 3 suggested changes. You mentioned further reducing the in-between wait time, which is currently 5 seconds. Should we try 1 s?

**Comment by f-brinkmann** [comment]
Hi Sergejs,

I merged this because I have only a limited time slot for finalizing the 1.0 release which is way more work than expected after a joint meeting with the Vienna group (see #25 for a bucket list).

- I reverted the special handling of the first instance in commit https://github.com/Any2HRTF/Mesh2HRTF/commit/0a4e56bfa6111d2df2d265662fb1182c55f159b1
- I introduced a second wait time and made it 1 second in commit https://github.com/Any2HRTF/Mesh2HRTF/commit/06b1ae572c03e440ca8e4579a4d66ceae7a8d9b4

Both is part of  #32 and would be easy to revert and continue the discussion at a later point, if you would suggest a different handling.

**Comment by SDX-LV** [comment]
all good.

**Pull request merged**
