### PR TITLE
Move all m-files to one folder

### PR DESCRIPTION
**Pull request by f-brinkmann**
Since we now have a Matlab *and* Python API it might be easier to understand, if we have all m-files in one folder and all py-files in an other folder. @germknoedlspeck what do you think?

### CODE REVIEW

**Comment by germknoedlspeck** [comment]
The problem is that all the functions for reading/writing evaluation grids and materials happen within a pre processing step, and Output2HRTF is the folder for post processing. @petibub, I think we need a more transparent file structure for the whole project :)

**Comment by petibub** [comment]
- The structure goes by the steps of the HRTF calculation process: 

- Mesh2Input: You have a mesh and want to prepare the input for the numerical calculations
- NumCalc: the numerical calculations
- Output2HRTF: the output of the calculations is converted to an HRTF set. 

All these steps are technology independent (Python, Matlab, C, Blender, text, whatever). Also, it's not related to any particular API. 

Can you explain why to diverge from that structure? Or maybe I just do not understand this issue?

**Comment by f-brinkmann** [comment]
It's more of a personal preference. I remember that I found it confusing as a new user to look for Matlab-Code in different places. Mesh2HRTF 0.4 needed this, because new evaluation grids had to be in the repository. In Mesh2HRTF 1.0, this is not the case anymore, so the code could also go somewhere else more easily.

In any case, It would be good to have the code in consistent locations. If the m-files stay there, I would also move the py-files there to make clear, that users can chose. This means we would also have the __init__.py files lying around in those directories. I think that was why I decided to gather the Pyhton code in one directory.

**Comment by germknoedlspeck** [comment]
Thanks to Sergejs, we now have a clear tutorial about the file structure. But if the code continuously grows and gets expanded with new features, I think we have to discuss the overall structure again (I'm not sure the Mesh2Input/NumCalc/Output2HRTF structure offers the full potential).

Also, a thought: Would it be an idea to .zip two different versions of Mesh2HRTF? i.e., Mesh2HRTF.m and .py? Because it may be unlikely for Matlab users wanting to use/see Python code and vice versa (?) - obviously, this does not account for the Blender scripts, they are independent of that point.

**Comment by f-brinkmann** [comment]
close, we decided to have a different project structure, see #25

**Pull request closed without merging**
